name = "cloudflare_pages_cleanup"
main = "src/index.ts"
compatibility_date = "2022-09-04"

# This worker will delete old deployments of Cloudflare Pages
#
# See README.md for details

[vars]
project_id="ahwoo-localhost" # name of one project to clean. Leave empty to clean all your projects.
                         # Cleaning all projects might not fit into the CPU limits of your plan.
                         # If you are on a free or bundled plan, you can set project_id to 
                         # "round-robin" and the cron trigger to "0 * * * *" to clean
                         # another project every other hour (or e.g. "* 3 * * *" to clean
                         # up to 60 projects between 3:00 am and 3:59 am)

# Wrangler only supports string values for variables
# Therefore we use a multiline value for the configuration in TOML format
config="""
   
[[rules]]                # the default rule
                         # as no "branches" or "projects" are defined, 
                         # this is a catch all for any deployment 
name = "Old Cleanup"     # optional, a name for debugging
maxVersions = 2          # delete any deployments over 10 versions on any branch of any project...
# maxDays = 30           # for anything over 30 days

# What follows are examples for more elaborated rules.
# Remember to insert such rules above the catch all rule if you want them to take effect.
# Down here they will never be executed because the above rule matches all projects and all branches.

[[rules]]                # This rule will prevent deletion of deployments 
                         # for the main branch of the blog project
name = "main_branch"     # optional, a name for debugging
projects = "ahwoo-localhost"        # only for the "blog" project
branches = ["main"]      # matches the main or master branch
maxDays = inf            # can be omitted: do not delete deployments based on age
maxVersions = 2        # can be omitted: do not delete deployments based on number of versions 

"""

[triggers]
# will run every sunday at noon, clean a new project every minute
crons = [ "0 */1 * * *" ]
